site_name: Thiccbois - Salt Documentation
site_description: Using saltstack a guide from 2 thiccbois
pages:
  - Home: index.md
  - 'Overview': overview.md
  - 'Getting Started': getting-started.md
  - 'Salt Cloud': salt-cloud.md
theme: spacelab
plugins:
    - search
    - markdownextradata
extra:
  customer:
    name: Your name here
    web: www.example.com
  salt:
    master: salt.example.com
    example:
      app_name: 'donkey-mule'