site_name: Thiccbois - Salt Documentation
site_description: Using saltstack a guide from 2 thiccbois
pages:
  - Home: index.md
  - 'Get Started':
      - 'Introduction': getting-started.md
      - 'Overview': overview.md
      - 'Commands': commands-overview.md
      - 'Profiles': profiles.md
      - 'Pillars': pillars.md
      - 'Formulas': formulas.md
  - 'Ops Manual' :
    - 'Salt Master': salt-master.md
    - 'Cloud': salt-cloud.md
    - 'Deploy - Rolling': deployment.md
    - 'Deploy - In-place': deployment-inplace.md
  - 'F.A.Q': faq.md
  - 'Contact': contact.md
theme: spacelab
plugins:
    - search
    - markdownextradata
extra:
  thiccbois:
    - name: Ross Crawford-d'Heureuse
      email: sendrossemail@gmail.com
    - name: Stefan Schweer
      email: s.schweer@heavycloud.de
  customer:
    name: Scantrust
    web: www.scantrust.com
  salt:
    version: 2018.3.0
    project: scantrust
    master: salt.scantrust.cc
    fqdn: scantrust.cc
    example:
      app_name: 'scantrust-api'
      partials:
        - qa-app*
        - qa-app-api*
      instances:
        - qa-app-api01.scantrust.cc
        - qa-app-worker01.scantrust.cc
        - qa-app-beat01.scantrust.cc
      profile_top: |
          base:
            '*':
              - profiles.base

            'qa-app-api*.example.com':
              - docker
              - scantrust
              - redis
              - rabbit
      pillar_top: |
          base:
            '*':
              - base
            #
            # scantrust-api
            #
            'qa-app-api*.example.com':
              - qa.scantrust.api
    cloud:
      profile:
        name: aws.seoul.conf
        path: /etc/salt/cloud.profiles.d/aws.seoul.conf
        data: |
          private_network_az_a:
            availability_zone: ap-northeast-2a
            image: ami-633d920d
            provider: ec2-northeast-2-vpc
            script: bootstrap-py3.sh
            securitygroupid:
            - sg-e9a97d83
            size: t2.micro
            ssh_username: ubuntu
            subnetid: subnet-ae7f53c6
          private_network_az_c:
            availability_zone: ap-northeast-2a
            image: ami-633d920d
            provider: ec2-northeast-2-vpc
            script: bootstrap-py3.sh
            securitygroupid:
            - sg-e9a97d83
            size: t2.micro
            ssh_username: ubuntu
            subnetid: subnet-4019890c
          public_network:
            image: ami-633d920d
            provider: ec2-northeast-2-vpc
            script: bootstrap-py3.sh
            securitygroupid:
            - sg-e9a97d83
            size: t2.micro
            ssh_username: ubuntu
            subnetid: subnet-3ea53172
          rabbitmq_az_a:
            extends: private_network_az_a
          rabbitmq_az_c:
            extends: private_network_az_c
          redis_az_a:
            extends: private_network_az_a
          redis_az_c:
            extends: private_network_az_c
          scantrust_api_az_a:
            extends: private_network_az_a
          scantrust_api_az_c:
            extends: private_network_az_c
          scantrust_worker_az_a:
            extends: private_network_az_a
          scantrust_worker_az_c:
            extends: private_network_az_c
    git:
      pillar: https://git.heavycloud.de/scantrust/salt-pillar
      profiles: https://git.heavycloud.de/scantrust/salt-profiles
      formulas:
        - name: scantrust-formula
          repo: https://git.heavycloud.de/scantrust/scantrust-formula
        - name: rabbitmq-formula
          repo: https://git.heavycloud.de/scantrust/rabbitmq-formula
        - name: redis-formula
          repo: https://git.heavycloud.de/scantrust/redis-formula
        - name: docker-formula
          repo: https://git.heavycloud.de/scantrust/docker-formula