site_name: Thiccbois - Salt Documentation
site_description: Using saltstack a guide from 2 thiccbois
pages:
  - Home: index.md
  - 'Get Started':
      - 'Introduction': getting-started.md
      - 'Overview': overview.md
      - 'Commands': commands-overview.md
      - 'Profiles': profiles.md
      - 'Pillars': pillars.md
      - 'Formulas': formulas.md
  - 'Ops Manual' :
    - 'Salt Master': salt-master.md
    - 'Cloud': salt-cloud.md
    - 'Rolling Deploy': deployment.md
      - 'Rollback': rollback.md
    - 'In-place Deploy': deployment-inplace.md
      - 'Rollback': rollback-inplace.md
  - 'F.A.Q': faq.md
  - 'Contact': contact.md
theme: spacelab
plugins:
    - search
    - markdownextradata
extra:
  thiccbois:
    - name: Ross Crawford-d'Heureuse
      email: sendrossemail@gmail.com
    - name: Stefan Schweer
      email: s.schweer@heavycloud.de  
  customer:
    name: Your name here
    web: www.example.com
  salt:
    version: 2018.3.0
    project: example
    master: salt.example.com
    fqdn: example.com
    example:
      app_name: 'my_awesome_app'
      partials:
        - qa-app*
        - qa-app-api*
      instances:
        - qa-app-api01.example.com
        - qa-app-worker01.example.com
        - qa-app-beat01.example.com
      profile_top: |
          base:
            '*':
              - profiles.base

            'qa-app-api*.example.com':
              - docker
              - my_awesome_app
              - redis
              - rabbit
      pillar_top: |
          base:
            '*':
              - base
            #
            # my_awesome_app
            #
            'qa-app-api*.example.com':
              - qa.my_awesome_app

    cloud:
      profile:
        name: aws.conf
        path: /etc/salt/cloud.profiles.d/aws.conf
        data: |
          private_network_az_a:
            availability_zone: ap-northeast-2a
            image: ami-633d920d
            provider: ec2-northeast-2-vpc
            script: bootstrap-py3.sh
            securitygroupid:
            - sg-e9a97d83
            size: t2.micro
            ssh_username: ubuntu
            subnetid: subnet-ae7f53c6
          private_network_az_c:
            availability_zone: ap-northeast-2a
            image: ami-633d920d
            provider: ec2-northeast-2-vpc
            script: bootstrap-py3.sh
            securitygroupid:
            - sg-e9a97d83
            size: t2.micro
            ssh_username: ubuntu
            subnetid: subnet-4019890c
          public_network:
            image: ami-633d920d
            provider: ec2-northeast-2-vpc
            script: bootstrap-py3.sh
            securitygroupid:
            - sg-e9a97d83
            size: t2.micro
            ssh_username: ubuntu
            subnetid: subnet-3ea53172
          example_api_az_a:
            extends: private_network_az_a
          example_api_az_c:
            extends: private_network_az_c
          example_worker_az_a:
            extends: private_network_az_a
          example_worker_az_c:
            extends: private_network_az_c
    git:
      pillar: https://github.com/example/salt-pillar
      profiles: https://github.com/example/salt-profiles
      formulas:
        - name: my_awesome_app-formula
          repo: https://github.com/example/my_awesome_app-formula
        - name: rabbitmq-formula
          repo: https://github.com/example/rabbitmq-formula
        - name: redis-formula
          repo: https://github.com/example/redis-formula
        - name: docker-formula
          repo: https://github.com/example/docker-formula