site_name: Thiccbois Salt Usage Documentation
site_description: Using saltstack a guide from 2 thiccbois
pages:
  - Home: index.md
  - 'Overview': overview.md
  - 'Getting Started': getting-started.md
  - 'Salt Cloud': salt-cloud.md
theme: readthedocs
extra:
  customer:
    name: Your name here
    web: www.example.com
    salt: salt.example.com